### PR TITLE
have partials interpreted as template inclusion in mustache_cli

### PR DESCRIPTION
**Pull request by gasche**
(Before this PR, any use of partials will fail in the command-line
tool.)

Partial names are turned into filenames by adding ".mustache" and then
resolveas paths relative to the current working directory (from which
the tool is invoked, not the directory where the template file
is located). For example, `{{>foo/bar}}` would include
"foo/bar.mustache".

This behavior is used by other command-line mustache processors,
typically the Ruby implementation (`gem install mustache`), so it is
somewhat-standard for a default behavior of partials.

Note: the Ruby implementation also supports {{> ../foo/bar}}, which is
not accepted by our current lexer (partial names must use dots in
a way that would be valid for other tags). The lexer could be relaxed
to allow those, but this can come as a later change.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Needs a CHANGES entry

**Comment by gasche** [comment]
After thinking more about this, I think that I would like to include two additional features before considering this PR as complete:

1. Relax the grammar of partial names to allow `./foo` and `../foo`.
2. Instead of resolving partials in the current working directory only, add a command-line option `-I dir/` to add `dir/` to the search path for template files. (This does not appear to be supported by the Ruby implementation I was using as reference, but the feature is provided (programmatically) in the [Go implementation](https://github.com/cbroglie/mustache#custom-partialprovider) -- see `FileProvider`).

I have pushed an additional commit to implement (1).

Regarding (2), my go-to command-line parsing tool would be cmdliner; @rgrinberg, does that work for you, or would you prefer to use another library or to wait for the cli to be in a separate package?

**Comment by rgrinberg** [comment]
Go ahead with using `cmdliner`. I'll do the package split before doing the release.

**Comment by gasche** [comment]
I have another feature coming in that builds on top of this one, so I decided to go ahead and merge before implementing support for include flags, which will hopefully come later.

**Pull request merged**
