### PR TITLE
Package split

### PR DESCRIPTION
**Pull request by rgrinberg**
Move mustache binary to a separate package to allow it to acquire extra deps.

@gasche did you make a decision on the package/binary name? I have no
preference, so I'll pick whatever you prefer.

### CODE REVIEW

**Comment by gasche** [comment]
My preference would be to not use `mustache` to avoid conflict with the semi-standard Ruby implementation. I don't have much of a preference as to which name to use (my only suggestion was `mustacho` and it's not, ahem, a particularly good one I think). If you were so inclined (and are willing to give it a week instead of a day), this sounds like something you could just ask the community about -- a Discuss thread or whatever -- also free publicity.

**Comment by gasche** [comment]
(For context, we are talking about issue #61, "Consider changing the binary name".) I guess `mustache-cli` is also an option, but it's weird as it is both different and completely generic.

**Comment by gasche** [comment]
(Thanks for the packaging work!)

**Comment by gasche** [comment]
The CI fails on this PR:

```
- File "mustache-cli/dune", line 10, characters 7-15:
- 10 |   (run mustache --help=groff)))
-             ^^^^^^^^
- Error: Program mustache not found in the tree or in PATH
-  (context: default)
```

**Comment by psafont** [comment]
The work has been merged as part of #71

**Pull request closed without merging**
