### PR TITLE
Port to jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by Armael** [comment]
Disclaimer: I know nothing about jbuilder.

A couple immediate questions:
- `_oasis` and `setup.*` are still there. Are we still using oasis on top of jbuilder?
- could we have a `make clean` rule?

**Comment by rgrinberg** [comment]
Using the makefile wrapper should be straightforward enough even if you aren't familiar.

Thanks, I removed _oasis and added a clean target. I don't think there any setup.* files checked in?

I will fix CI now.

**Comment by Armael** [comment]
Thanks. Yeah, the `setup.*` were probably build leftovers from my end. You updated the `.gitignore` so everything's good.

**Comment by Armael** [comment]
By curiosity, what does the topkg support do?

**Comment by rgrinberg** [comment]
I'm not an expert here, but I mainly use it for linting my repo with `$ topkg lint` (try that out).

It's mainly useful for releasing (`$ topkg help release`)

**Comment by Armael** [comment]
Well, I must say compilation is very fast, as advertised :). How do I compile the examples?

**Comment by rgrinberg** [comment]
`$ make` should build the examples already. Or if you want just the examples: `$ jbuilder build @DEFAULT`

**Comment by Armael** [comment]
Alright. LGTM then (after fixing the build failure on 4.05 reported by travis I guess?).

**Comment by rgrinberg** [comment]
Looks like it's just some nonsense:

```
[uchar.0.0.1] https://github.com/ocaml/uchar/releases/download/v0.0.1/uchar-0.0.1.tbz downloaded
[ERROR] The sources of the following couldn't be obtained, aborting:
          - sexplib.v0.9.1
        (This may be fixed by running 'opam update')
'unset TESTS; OPAMYES=1 export OPAMYES; OPAMBUILDTEST=1 export OPAMBUILDTEST; set -ue; opam install mustache --deps-only' exited 66. Terminating with 66
```

Note that travis passed on 4.05 on the previous build and i didn't edit the code or the build

**Comment by Armael** [comment]
Oh, alright then.

**Pull request merged**
